### ISSUE TITLE
discussion of full on AWS vs lightsail, DO, linode, ...

### ISSUE THREAD

**Issue by stephenturner** [uvasomrc/courses#2]
The cloud class would benefit from a discussion of using AWS S3/EBS/EC2/... compared to AWS's own lightsail, or others like linode, DO, etc.

- https://amazonlightsail.com/pricing/
- https://www.linode.com/pricing
- https://www.digitalocean.com/pricing/

See also: [$5 Showdown: Linode vs. DigitalOcean vs. Amazon Lightsail vs. Vultr](https://joshtronic.com/2017/02/14/five-dollar-showdown-linode-vs-digitalocean-vs-lightsaild-vs-vultr/).

**Comment by nmagee** [comment]
This is a good suggestion -- we will try to incorporate that differentiation in this Fall's iteration of the workshop.
