### ISSUE TITLE
HPC / CLI / Matlab / Afternoon Overview Workshop

### ISSUE THREAD

**Issue by nmagee** [uvasomrc/courses#4]
Here's an agenda we should expand fully and put in the right order. Please modify:

- Introduction to CLI - slides & discussion
- Basic CLI operations: 
    - file and folder manipulation
    - piping, redirecting
    - other things
- Environment
    - vars and setting them
    - bin / $PATH
    - modules
    - storage locations & scratch
- Basic Scripting
    - #!/bin/bash
    - chmod
    - full paths
- Intro to HPC - slides & discussion
    - Architecture - head nodes and workers
    - /scratch
    - Allocations
- Matlab Scripting & Compiling
  ...
  ...

**Comment by cagancayco** [comment]
Neal
- Introduction to CLI - slides & discussion
- Basic CLI operations: 
    - file and folder manipulation
    - piping, redirecting
    - other things, text editor options?

Hardik
- Environment
    - vars and setting them
    - bin / $PATH
    - modules
    - storage locations & scratch
    - Globus
- Basic Scripting
    - #!/bin/bash
    - chmod
    - full paths

Christina
- Intro to HPC - slides & discussion
    - Architecture - head nodes and workers
    - /scratch
    - Allocations
- Bash/Matlab Scripting & Compiling
    - Writing job submission script for cab-cluster
    - Comparing TORQUE/SLURM
    - Writing slurm script for Rivanna
    - Compare torque/slurm parallel
    - Feeding LS-DYNA output into Matlab
    - Compiling Matlab standalone executable
    - Running Matlab executables

**Comment by nmagee** [comment]
@parikhhi See above
